version: 2
linters:
  default: standard
issues:
  exclude-rules:
    # Exclude mage's temporary compilation output file if it ever appears.
    # This prevents errors if linters/formatters try to process it.
    - path: mage_output_file.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
